version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elixir_notes_app_dev
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: elixir_notes_app
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/elixir_notes_app_dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: ["mix", "phx.server"]
